---
- hosts: all
  # TODO: be vagrant, not root, unless needed
  become: true
  gather_facts: false
  tasks:
  - name: Update Apt
    apt:
      update_cache: true
      cache_valid_time: 1500
  - name: Install X Server stuff
    apt: name={{item}} state=latest
    with_items:
    # think this enables copy-paste between guest/host
    - virtualbox-guest-dkms
    - xinit
    - git

  - name: Push folder_state to remote hosts
    copy:
      src: /home/vagrant/folder_state.py
      dest: /home/vagrant/folder_state.py

  # TODO: prune this down?
  - name: Install things Apt says i3 needs
    apt: name={{item}} state=latest
    with_items:
    - dunst
    - feh # for mah wallpapers
    - i3lock
    - i3status
    - libanyevent-i3-perl
    - libanyevent-perl
    - libasound2
    - libasound2-data
    - libasync-interrupt-perl
    - libasyncns0
    - libcommon-sense-perl
    - libconfuse-common
    - libconfuse0
    - libev-perl
    - libflac8
    - libguard-perl
    - libjson-xs-perl
    - libogg0
    - libpulse0
    - libsndfile1
    - libtypes-serialiser-perl
    - libvorbis0a
    - libvorbisenc2
    - libxcb-dpms0
    - libxdg-basedir1
    - suckless-tools

  # https://github.com/Airblader/i3/wiki/Compiling-&-Installing
  - name: Git i3-gaps
    become_user: vagrant
    git:
      repo: https://www.github.com/Airblader/i3
      dest: ~/Git/i3-gaps
  # http://docs.ansible.com/ansible/latest/apt_repository_module.html
  - name: Add libxcb-xrm-dev PPA
    apt_repository:
      repo: 'ppa:aguignard/ppa'
      update_cache: true
  - name: Get i3-gaps dependencies
    apt: name={{item}} state=latest
    with_items:
    - libxcb1-dev
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libev-dev
    - libxcb-cursor-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - autoconf
    - libxcb-xrm-dev
  - name: autoreconf it
    command: autoreconf --force --install
    args:
      chdir: /home/vagrant/Git/i3-gaps/
      creates: /home/vagrant/Git/i3-gaps/Makefile.in
  - name: make the build folder
    file:
      path: /home/vagrant/Git/i3-gaps/build
      state: directory
  - name: configure it
    command: ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    args:
      chdir: /home/vagrant/Git/i3-gaps/build/
      creates: /home/vagrant/Git/i3-gaps/build/Makefile
  - name: make it
    command: make
    args:
      chdir: /home/vagrant/Git/i3-gaps/build/
      creates: /home/vagrant/Git/i3-gaps/build/i3
  - name: make install
    command: make install
    args:
      chdir: /home/vagrant/Git/i3-gaps/build/
      creates: /usr/bin/i3
  # TODO: will be replaced by the stow method for all of my configs
  - name: make the i3 config folder
    file:
      path: /home/vagrant/.config/i3
      state: directory
  - name: Push i3 config to remote hosts
    copy:
      src: /home/vagrant/.config/i3/config
      dest: /home/vagrant/.config/i3/config
  - name: make the Pictures dir
    file:
      path: /home/vagrant/Pictures
      state: directory
  - name: Push i3 Wallpaper
    copy:
      src: /home/vagrant/Pictures/1asx18foouaz.jpg
      dest: /home/vagrant/Pictures/1asx18foouaz.jpg

  - name: Make it the default window manager
    alternatives:
      name: x-window-manager
      path: /usr/bin/i3
      link: /usr/bin/x-window-manager

